export const INITIAL_STATES_SET_USER = 'INITIAL_STATES_SET_USER'

// informations
export const CREATE_INFORMATION = 'CREATE_INFORMATION'
export const UPDATE_INFORMATION = 'UPDATE_INFORMATION'
export const DELETE_INFORMATION = 'DELETE_INFORMATION'

// users
export const FETCH_LIST_USERS = 'FETCH_LIST_USERS'
export const FETCH_USER = 'FETCH_USER'
export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const SEARCH_USERS = 'SEARCH_USERS'


// cards
export const FETCH_LIST_CARDS = 'FETCH_LIST_CARDS'
export const FETCH_CARD = 'FETCH_CARD'
export const CREATE_CARD = 'CREATE_CARD'
export const UPDATE_CARD = 'UPDATE_CARD'

// companies
export const FETCH_COMPANY = 'FETCH_COMPANY'
export const FETCH_COMPANY_USERS = 'FETCH_COMPANY_USERS'
export const FETCH_COMPANY_CARDS = 'FETCH_COMPANY_CARDS'
export const FETCH_LIST_COMPANIES = 'FETCH_LIST_COMPANIES'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'
export const CREATE_COMPANY = 'CREATE_COMPANY'

// contacts
export const FETCH_LIST_CONTACTS = 'FETCH_LIST_CONTACTS'
