export const INITIAL_STATES_SET_USER = 'INITIAL_STATES_SET_USER'

export const CREATE_INFORMATION = 'CREATE_INFORMATION'

export const CREATE_USER = 'CREATE_USER'

export const FETCH_CARD = 'FETCH_CARD'
